name: Build Payloads

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.2.12479018"

      - name: Configure NDK
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> $GITHUB_ENV

      - name: Show repository
        run: |
          pwd
          ls -la
          ls src/targets

      - name: Build all targets
        run: |
          mkdir -p artifacts

          for dir in src/targets/*; do
            [ -d "$dir" ] || continue

            TARGET=$(basename "$dir")

            echo "========================="
            echo "Building $TARGET"
            echo "========================="

            make clean || true
            make TARGET="$TARGET"

            mkdir -p artifacts/$TARGET

            cp build/$TARGET/cve-2026-43499-app.so artifacts/$TARGET/ 2>/dev/null || true
            cp build/$TARGET/cve-2026-43499-app.release.so artifacts/$TARGET/ 2>/dev/null || true
            cp build/$TARGET/cve-2026-43499-root artifacts/$TARGET/ 2>/dev/null || true
          done

      - uses: actions/upload-artifact@v4
        with:
          name: payloads
          path: artifacts